# Generated by Django 5.0 on 2025-03-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
