# Generated by Django 5.0 on 2025-03-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_alter_entrada_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/imagenes/entradas', verbose_name='Imagen'),
        ),
    ]
