# Generated by Django 5.0 on 2025-03-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_entrada_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(upload_to='static/assets/imagenes/entradas', verbose_name='Imagen'),
        ),
    ]
